event/urls.py
from django.conf.urls import url
from .views import home, event_detail, error, event_list, event_create, event_delete, event_update


urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^list/$', event_list, name="list"),
    url(r'^detail/(?P<event_slug>[-\w]+)/$', event_detail, name="details"),
    url(r'^create/$', event_create, name="create"),
    url(r'^(?P<event_slug>[-\w]+)/update/$', event_update, name="update"),
    url(r'^delete/(?P<event_slug>[-\w]+)/$', event_delete, name="delete"),
    url(r'^error/$', error, name="error"),
]

main_event/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include('event.urls', namespace='events_app')),
]

event/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.core.urlresolvers import reverse

from datetime import datetime
# Create your models here.

city_choices = [('DURHAM', 'Durham'), ('RALEIGH', 'Raleigh')]

# now = datetime.strptime(str(timezone.now), "%H:%M")

class EventManager(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=140, unique=True, blank=True, null=True)
    description = models.TextField()
    # Images =
    # music_category = models.CharField(max_length=500)
    # music_sample =
    # dj_name = models.CharField(max_length=500)
    event_start_time = models.TimeField(default=timezone.now)
    event_end_time = models.TimeField(default=timezone.now)
    event_date = models.DateField(default=timezone.now)
    post_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("events_app:details", kwargs={'event_slug': self.slug})

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while EventManager.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save()


class EventLocation(models.Model):
    title = models.OneToOneField(EventManager, on_delete=models.CASCADE)
    venue = models.CharField(max_length=550, null=True, blank=True)
    address = models.CharField(max_length=300)
    zip_code = models.CharField(max_length=10)
    states = models.CharField(default="North Carolina", max_length=20, editable=False)
    city = models.CharField(choices=city_choices, max_length=10, default='Select')

    def __str__(self):
        return self.address


        # import psycopg2
        #
        # try:
        #     conn = psycopg2.connect("dbname='event_hunt' user='postgres' host='localhost' password='stunner'")
        #     cur = conn.cursor()
        #     cur.execute("select * from states")
        #     rows = cur.fetchall()
        #     states_choices = [(j,j) for i in rows for j in i]
        #
        # except:
        #     print ("I am unable to connect to the database")

event/forms.py
from django import forms
from django.contrib.admin import widgets
from .models import EventLocation, EventManager


class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'

class EventManagerForm(forms.ModelForm):

    class Meta:
        model = EventManager
        fields =['title', 'description', 'event_start_time', 'event_end_time', 'event_date']

        widgets = {
            'event_date': DateInput(),
            'event_start_time': TimeInput(),
            'event_end_time': TimeInput(),
        }

    # def __init__(self, *args, **kwargs):
    #     super(EventManagerForm, self).__init__(*args, **kwargs)
    #     self.fields['event_date'].widget = widgets.AdminDateWidget()
    #     self.fields['event_start_time'].widget = widgets.AdminTimeWidget()
    #     self.fields['event_end_time'].widget = widgets.AdminTimeWidget()


class EventLocationForm(forms.ModelForm):

    class Meta:
        model = EventLocation
        fields = ['address', 'city', 'zip_code']

event/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponseRedirect
from django.http import Http404
from .models import EventManager, EventLocation
from django.db.models import Q
from.forms import EventManagerForm, EventLocationForm

import datetime

# Create your views here.

def home(request):

    latest_events = EventManager.objects.filter(event_date__gte=datetime.datetime.today())  #order_by('-event_date')[:5]
    context = {'latest_events': latest_events}
    return render(request, 'event/home.html', context)


def event_list(request):
    events = EventLocation.objects.all()[::-1]
    query = request.GET.get("q")
    text = ''
    if query:
        events = EventLocation.objects.all()
        events = events.filter(
            Q(address__icontains=query) |
            Q(states__icontains=query) |
            Q(city__icontains=query) |
            Q(zip_code__icontains=query) |
            Q(title__title__icontains=query)|
            Q(title__description__icontains=query)
        ).distinct()[::-1]

        if not events:
            text = "Oops! No results found. Try again!"

    context = {"event_list": events, 'text': text}
    return render(request, "event/list.html", context)


def event_detail(request, event_slug):
    if not request.user.is_active or not request.user.is_authenticated:
        return redirect("events_app:error")
    event = get_object_or_404(EventManager, slug=event_slug)
    address = EventLocation.objects.get(title_id=event.id)
    context = {'event': event, 'address': address}
    return render(request, 'event/detail.html', context)


def event_create(request):
    if not request.user.is_active or not request.user.is_authenticated:
        return redirect("events_app:error")
    form1 = EventManagerForm(request.POST or None)
    form2 = EventLocationForm(request.POST or None)

    if form1.is_valid() and form2.is_valid():
        instance1 = form1.save(commit=False)
        instance2 = form2.save(commit=False)
        instance1.save()
        instance2.title_id = instance1.id
        instance2.save()
        return HttpResponseRedirect(instance1.get_absolute_url())

    context = {"form1": form1, "form2": form2}
    return render(request, 'event/event_form.html', context)

def event_update(request, event_slug):
    if not request.user.is_active or not request.user.is_authenticated:
        return redirect("events_app:error")
    main_instance = get_object_or_404(EventManager, slug=event_slug)
    location_instances = get_object_or_404(EventLocation, title_id= main_instance.id)
    form1 = EventManagerForm(request.POST or None, instance=main_instance)
    form2 = EventLocationForm(request.POST or None, instance=location_instances)

    if form1.is_valid() and form2.is_valid():
        instance1 = form1.save(commit=False)
        instance2 = form2.save(commit=False)
        instance1.save()
        instance2.title_id = instance1.id
        instance2.save()
        return HttpResponseRedirect(instance1.get_absolute_url())

    context = {"form1": form1, "form2": form2}
    return render(request, 'event/event_form.html', context)

def event_delete(request):
    pass

def error(request):
    return render(request, 'event/error.html', context={})

event/templates/event/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link href="{% static 'css/MyCss.css' %}" rel="stylesheet">
    <style>

      {% block style %}

      {% endblock %}

    </style>
  </head>
  <body>

    <header class="myHeader myHeader1">
      <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <a class="navbar-brand" href="#"><img  class="mylogo" src="{% static 'img/new_logo.png' %}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse  container" id="navbarCollapse">
          <ul class="navbar-nav mr-auto ">
            <li class="nav-item">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Events</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Promote</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Feedback</a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0 mybtn" type="submit">Search</button>
          </form>
        </div>
      </nav>

      {% block heroText %}

      {% endblock %}


    </header>

    <main role="main">

      <div id="myCarousel" class="carousel slide" data-ride="carousel">
          {% block carousel %}

          {% endblock %}
      </div>


      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container event-detail">

          {% block event-detail %}


          {% endblock %}
        </div>

      <div class="container marketing">


        <!--<form class="form-inline mt-2 mt-md-0">-->
            <!--<input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
            <!--<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
          <!--</form>-->
        <!-- Three columns of text below the carousel -->
        <div class="row">

          {% block recent-events %}


          {% endblock %}
        </div><!-- /.row -->


        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        {% block features %}

        {% endblock %}
        <!-- /END THE FEATURETTES -->

      </div><!-- /.container -->


      <!-- FOOTER -->
      <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2017 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </main>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>

event/templates/event/detail.html
{% extends 'event/base.html' %}
{% load staticfiles %}

{% block style %}

.myHeader1 {
    background-image: linear-gradient(rgba(0, 0, 0, 0.70), rgba(0, 0, 0, 0.40) ), url({% static 'img/detroit.jpg' %});
    height: 70vh;
    top: 0;
}

.myHeader1 .event-title {
    position: absolute;
    display: block;
    float: right;
    bottom: 40%;
    right: 10%;
    border: 1px solid #ddd;

}


.ad-statement {
    font-size: 1.3em;
    color: #ddd;
    padding: 5%;
    margin-bottom: 0;
}

.posted {
    position: relative;
    display: block;
    font-size: 1em;
}

.event-detail h4{
    line-height: 2.5px;
}

{% endblock %}


{% block heroText %}
        <div class="event-title">
            <h3 class='ad-statement'>
                Event Date: {{event.event_date}}<br><br>
                Timings: {{event.event_start_time}} to {{event.event_end_time}}
            </h3>
        </div>
{% endblock %}


{% block event-detail %}
<h1>{{ event.title }}</h1>
<p class="posted">Posted on: {{event.post_date }}</p>

<h5>{{ address.venue }},<br>
{{ address.address }},<br>
{{ address.states }}, {{ address.city }}, {{ address.zip_code }}</h5><br><br>
{{ event.description }}<br><br><br>

<h5>Some images from previous events: </h5>

<h5> Dj's Sample Music: </h5>
{% endblock %}

event/templates/event/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
<h1> Login If you want to view content </h1>
<a href="{% url 'events_app:home' %}">back to home</a>
</body>
</html>

event/templates/event/event_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form</title>
</head>
<body>
    <form method="POST" action=""> {% csrf_token %}
        {{ form1.as_p }}
        {{ form2.as_p }}
        <input type="submit" value="Create Event" >
    </form>
</body>
</html>

event/templates/event/home.html
{% extends 'event/base.html' %}
{% load staticfiles %}


{% block heroText %}
        <div class="container hero-text">
            <h1 class='ad-statement'><span class="beats"><img src="{% static 'img/beats.png' %}"></span> Best place to find <br>music events near you </h1>
                <a class='explore_link' href="#">&#128269; let's Explore</a>
        </div>
{% endblock %}



{% block recent-events %}
<h1>List of Top 5 Events this Month <span><p style="font-size: 0.5em">(Explore more events in Events tab)</p></span></h1>
    {% for event in latest_events %}
        <div class="col-lg-12 recent-12-div">

            <h2 class="recent-12-title">{{ event.title }} </h2>  <!-- |truncatechars:20 -->
            {% for location in event.eventlocation_set.all %}
                <p style="text-align: left">{{ location.city }}, {{ location.states }}, {{ location.zip_code }}</p>
            {% endfor %}
            <img class="recent-12" src="{% static 'img/hardwell.jpg'%}" alt="Generic placeholder image" width="100%" height="auto">
            <p class="recent-12-text"><a class="explore_link" href="{{ event.get_absolute_url }}" role="button">View Event&raquo;</a></p>
          </div><!-- /.col-lg-4 -->
    {% endfor %}



{% endblock %}

{% block features %}

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5 order-md-1">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
          </div>
          <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
          </div>
        </div>

        <hr class="featurette-divider">
        {% endblock %}

<!--<p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>-->

event/templates/event/list.html
{% extends 'event/base.html' %}

{% load staticfiles %}

{% block style %}

.myHeader1 {
    background-image: none;
    min-height: 100vh;
    top: 0;
}

.event-list{
    position: relative;
    margin-top: 5%;
    height: 100%;
    width: 100%;
}

.event-inner{
    padding: 2%;
}

.event-inner .no-result {
    margin-left: 20%;
}

.myform {

    margin-left: 20%;
}


.test{
    width: 50%;
}

.image-list {
    width: inherit;
    height: auto;
    box-shadow: 2px 2px 5px #222;
}

{% endblock %}


{% block heroText %}

<div class="event-list">
    <div class="event-inner">
        <form class="form-inline mt-2 mt-md-0 myform">
            <input class=" test mr-sm-2" name='q' type="text" placeholder="Search by City, state, zip, event-name" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0 mybtn" type="submit">Search</button>
    </form>
        <br><br>
    <p class="no-result">{{text}}</p>
    {% for event in event_list %}
        <div class = " col-lg-4 all-events ">
            <h3><a href="{{ event.title.get_absolute_url }}">{{ event.title |truncatechars:20}}</a></h3>
            <p>{{ event.city }}, {{ event.states }} {{event.zip_code}} </p>
            <img class= "image-list" src="{% static 'img/hardwell.jpg'%}"/>
        </div>
    {% endfor %}

<!--<form action="">-->

    <!--<input name="q" type="text">-->
    <!--<input type="submit" value="Search">-->

<!--</form>-->
    </div>
</div>
{% endblock %}

event/templates/event/upcoming.html
{% extends 'event/base.html %}

{% block carousel %}}

    <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
            <div class="container">
              <div class="carousel-caption text-left">
                <h1>Example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1>Another example headline.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
            <div class="container">
              <div class="carousel-caption text-right">
                <h1>One more for good measure.</h1>
                <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>

{% endblock %}